name: CI (Maven)

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]
  workflow_dispatch:
concurrency:
  group:
    ${{ github.repository }}-${{ github.workflow }}-${{ github.event.number || github.head_ref || github.run_id || github.sha }}
  cancel-in-progress: true
permissions:
  contents: write

jobs:
  build:
    name: Build on ${{ matrix.os }} with Java ${{ matrix.java }}
    strategy:
      fail-fast: false
      matrix:
        java: [ 8, 11 ]
        os: [ ubuntu-24.04, ubuntu-24.04-arm,  macos-13 ]

    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up JDK ${{ matrix.java }}
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: ${{ matrix.java }}
          cache: 'maven'

      - name: Build with Maven (skip integration tests & quality checks)
        run: ./mvnw -B -V -DskipITs=false -DskipQuality=false verify
